name: Update streak stats

on:
  schedule:
    - cron: "0 */4 * * *"  # 3:00 PM hora México (UTC-6)
  push:
    paths:
      - ".github/workflows/streak-stats.yml"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Generate streak stats
        uses: DenverCoder1/github-readme-streak-stats@main
        with:
          options: user={{ github.repository_owner }}&theme=github-dark&date_format=M%20j%2C%20Y
          #options: user=taquero-programador&theme=github-dark&date_format=M%20j%2C%20Y
          path: profile/streak.svg
          token: ${{ secrets.STREAK_TOKEN }}

      - name: Commit streak stats
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41521299+github-actions[bot]@users.noreply.github.com"
          git add profile/streak.svg
          
          if [[ -z $(git status --porcelain) ]]; then
            echo "Sin cambios, no hay nada que hace."
          else
            git commit -m "Update streak stats"
            git pull --rebase origin main
            git push origin main
          fi
